Fix printf security compilation warning/error
Fix the following GCC compilation error when the -Wformat-security and
-Werror=format-security flags are used:

main.c: In function 'info_msg':
main.c:97:3: error: format not a string literal and no format arguments [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wformat-security-Werror=format-security8;;]
   97 |   printf(msg);
      |   ^~~~~~